apiVersion: 1

datasources:
  - name: Postgres              # any readable label, doesn't need to match
    type: postgres
    uid: afscz4el7e8zkf         # this must match the .json file in the dashbaords folder
    url: db:5432
    user: ${POSTGRES_USER}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
    secureJsonData:
      password: ${POSTGRES_PASSWORD}